//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GhostHuntAR.Infrastructure.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GhostHuntAR.Infrastructure.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DELETE FROM SavedSearches WHERE UserId = {0};.
        /// </summary>
        internal static string DeleteSavedSearchesByUserId {
            get {
                return ResourceManager.GetString("DeleteSavedSearchesByUserId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WITH temp AS (SELECT DISTINCT GHLocationID 
        ///FROM Sounds
        ///WHERE UserName = {0}
        ///
        ///UNION
        ///
        ///SELECT DISTINCT GHLocationID 
        ///FROM Images
        ///WHERE UserName = {0}
        ///
        ///UNION
        ///
        ///SELECT DISTINCT GHLocationID 
        ///FROM Texts
        ///WHERE UserName = {0})
        ///
        ///SELECT ghl.*, 
        ///(SELECT COUNT(*) FROM Sounds WHERE GHLocationID = ghl.GHLocationID) AS &apos;SoundsCount&apos;,
        ///(SELECT COUNT(*) FROM Images WHERE GHLocationID = ghl.GHLocationID) AS &apos;ImagesCount&apos;,
        ///(SELECT COUNT(*) FROM Texts WHERE GHLocationID = ghl.GHLocationID) AS &apos;TextsCount&apos;
        ///FR [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GetDistinctLocationIdsSightsAndSounds {
            get {
                return ResourceManager.GetString("GetDistinctLocationIdsSightsAndSounds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WITH temp AS (SELECT TOP({3}) *, ( 6371 * acos( cos( radians({0}) ) * cos( radians( Latitude ) ) * cos( radians( Longitude ) - radians({1}) ) + sin( radians({0}) ) * sin( radians( Latitude ) ) ) ) as Distance
        ///FROM GHLocations)
        ///
        ///SELECT *
        ///FROM temp
        ///WHERE Distance &lt; {2}
        ///ORDER BY Distance;
        ///
        ///.
        /// </summary>
        internal static string LocationsByDistance {
            get {
                return ResourceManager.GetString("LocationsByDistance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WITH temp AS (SELECT TOP({3}) *, ( 6371 * acos( cos( radians({0}) ) * cos( radians( Latitude ) ) * cos( radians( Longitude ) - radians({1}) ) + sin( radians({0}) ) * sin( radians( Latitude ) ) ) ) as Distance
        ///FROM GHLocations)
        ///
        ///SELECT GHLocationID,
        ///CONVERT(NVARCHAR(30), DateLastModified, 127) AS DateLastModified
        ///FROM temp
        ///WHERE Distance &lt; {2}
        ///ORDER BY Distance;
        ///
        ///.
        /// </summary>
        internal static string LocationStatusesByDistance {
            get {
                return ResourceManager.GetString("LocationStatusesByDistance", resourceCulture);
            }
        }
    }
}
